<?php
/** @var \Domus\CustomerDeliveryChecker\Block\Adminhtml\Pincode\Export $block */
?>
<div class="export-pincodes">
    <h2><?php echo __('Export Pincodes to CSV'); ?></h2>
    <form action="<?php echo $block->getExportUrl(); ?>" method="post">
        <?php echo $block->getBlockHtml('formkey'); ?>
        <button type="submit" class="action-primary"><?php echo __('Download CSV'); ?></button>
    </form>
</div>
